version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_SOURCE_VERSION
      - echo Build started on `date`
  build:
    commands:
      - echo Build started on `date`
      - echo Installing dependencies...
      # Add your build commands here
      # Example for Node.js:
      # - npm install
      # - npm run build
      # - npm test
      # Example for Docker:
      # - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      # - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      # Example for Docker push:
      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      
artifacts:
  files:
    - '**/*'
  # name: myapp-$(date +%Y-%m-%d)
  
cache:
  paths:
    - '/root/.npm/**/*'
    # Add other cache paths as needed